name: Codecov

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    env:
      OS: ubuntu-latest
      PYTHON: "3.8"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python "3.8"
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install tox
        run: python -m pip install --upgrade pip setuptools wheel tox

      - name: Run tox
        run: tox -e py

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: "."
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true
